force-app/main/default/objects/TestDriveAppoinmentFlyout__e/TestDriveAppoinmentFlyout__e.object-meta.xml
<CustomObject>
    <label>TestDriveAppoinmentFlyout</label>
    <pluralLabel>TestDriveAppoinmenstFlyout</pluralLabel>
</CustomObject>

force-app/main/default/objects/TestDriveAppoinmentFlyout__e/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>AccountName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDriveAppoinmentFlyout__e/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDriveAppoinmentFlyout__e/fields/InputType__c.field-meta.xml
<CustomField>
    <fullName>InputType__c</fullName>
    <label>InputType</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDriveAppoinmentFlyout__e/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>ServiceDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/clsAppoinmentController.cls
public with sharing class clsAppoinmentController {
    
    // Method to publish platform event
    @InvocableMethod(label='Appoinment handler' description='Appoinment Platform event fireing class')
    public static void publishAppoinment(List<Request> requests) {
        
        Request input = requests[0];
        String inputContactId = input.ContactId;
        
        system.debug('inside publishAppointment');
        
        TestDriveAppoinmentFlyout__e  tsAp = New TestDriveAppoinmentFlyout__e();
        
        tsAp.ContactId__c=inputContactId;
        tsAp.InputType__c=input.inputType;
        tsAp.AccountName__c=input.AccountName;
        tsAP.ServiceDate__c=  input.ServiceDate;
        
        system.debug('contact'+tsAp.ContactId__c);
        system.debug('inputType'+tsAp.InputType__c);
        system.debug('AccountName'+tsAp.AccountName__c);
        
        Database.SaveResult sr = EventBus.publish(tsAp);
        
        // Add logger to check if the event is published successfully
        if (sr.isSuccess()) {
            System.debug('Event published successfully: ' + sr.getId());
        } else {
            for (Database.Error error : sr.getErrors()) {
                System.debug('Failed to publish event: ' + error.getStatusCode() + ' - ' + error.getMessage());
            }
            
        }
    }
    public class Request {            
        @InvocableVariable(label='contactId')
        public String ContactId;    
        
        @InvocableVariable(label='inputType')
        public String inputType;    
        
        @InvocableVariable(label='AccountName')
        public String AccountName;   
        
         @InvocableVariable(label='ServiceDate')
        public Date ServiceDate;    
        
        
        
        
        
        
    }   
    
}